import { ITask } from './interfaces/interfaces';

export const userProfile = {
    name: 'Вильгельмина',
    surname: 'Шавшина',
    avatarPath: '/avatar.png',
};
export const TASKS: ITask[] = [
    {
        key: 'TR-321',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Разработка нового компонента для отображения графиков',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '5ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-322',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Рефакторинг кода модуля авторизации',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '2ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-121',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Устранить проблемы с кроссбраузерной совместимостью',
        category: 'errors',
        iconBgColor: '#e27475',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-122',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Ошибка валидации формы при пустом поле “номер телефона”',
        category: 'errors',
        iconBgColor: '#e27475',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-123',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content:
            'Неверное поведение компонента “Главный экран”  при изменении размера окна',
        category: 'errors',
        iconBgColor: '#e27475',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '5ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-124',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content:
            'Ошибка при обработке события клика (несоответствие контекста)',
        category: 'errors',
        iconBgColor: '#fecdd3',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-125',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Невозможно загрузить динамически импортируемые модули',
        category: 'errors',
        iconBgColor: '#A90C26',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '12ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-126',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: undefined,
        content: 'Отсутствует лоадер при загрузке списка вопросов',
        category: 'errors',
        iconBgColor: '#e27475',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '12ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-127',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: undefined,
        content: 'Адаптация макетов под различные устройства',
        category: 'general',
        department: 'diagram',
        iconBgColor: '#39B39D',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '5ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-128',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: undefined,
        content: 'Создание многоуровневого выпадающего меню',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '1ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-129',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: undefined,
        content: 'Создание кастомного компонента для загрузки файлов',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Ревью', engTitle: 'review' },
        spentTime: '',
        plannedTime: '30 м',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-130',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: undefined,
        content: 'Подключение и настройка системы международных переводов',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '12ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-133',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: undefined,
        content: 'Интеграция с системой аутентификации через OAuth',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-345',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: undefined,
        content: 'Создание адаптивной версии страницы Профиль',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Ревью', engTitle: 'review' },
        spentTime: '',
        plannedTime: '',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-333',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: undefined,
        content: 'Верстка страницы Отпуска и Больничные',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '24ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-321',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'pending',
        assignee: undefined,
        content: 'Возможность брать больничные не админу',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '10ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-323',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'in-progress',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Разработка нового интерфейса для панели управления',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Ревью', engTitle: 'review' },
        spentTime: '',
        plannedTime: '8ч 53м',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'completed' },
            { label: 'Этап 3', step: 'in-progress' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-401',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'paused',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Drag n drop доступен не админам',
        category: 'errors',
        iconBgColor: '#A90C26',
        status: { title: 'Согласование', engTitle: 'coordination' },
        spentTime: '1ч',
        plannedTime: '2ч',
        stages: [
            { label: 'Этап 1', step: 'paused' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
            { label: 'Этап 4', step: 'pending' },
        ],
    },
    {
        key: 'TR-47',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'paused',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content:
            'Не отображается дефолтная иконка, если пользователь при создании проекта не загрузил свою',
        category: 'errors',
        iconBgColor: '#B0B0B0',
        status: { title: 'Ревью', engTitle: 'review' },
        spentTime: '1ч',
        plannedTime: '2ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'paused' },
            { label: 'Этап 3', step: 'pending' },
        ],
    },
    {
        key: 'TR-31',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'paused',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Создание адаптивной версии главной страницы',
        category: 'general',
        department: 'hashtag',
        iconBgColor: '#899da7',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '1ч',
        plannedTime: ' 4ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
        ],
    },
    {
        key: 'TR-33',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'paused',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Разработка и интеграция формы обратной связи',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '25м',
        plannedTime: '1ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
        ],
    },
    {
        key: 'TR-35',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'paused',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Улучшение производительности рендеринга страницы',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Ревью', engTitle: 'review' },
        spentTime: '5ч',
        plannedTime: '10ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
        ],
    },
    {
        key: 'TR-36',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'paused',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Рефакторинг CSS и SCSS для улучшения читаемости',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '50м',
        plannedTime: '1ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
        ],
    },
    {
        key: 'TR-37',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'paused',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Разработка модального окна для подтверждения действий',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '3ч',
        plannedTime: '4ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
        ],
    },
    {
        key: 'TR-38',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'paused',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Интеграция анимаций при прокрутке страницы',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '2ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
        ],
    },
    {
        key: 'TR-39',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'paused',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content:
            'Оптимизация загрузки изображений с использованием lazy loading',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Ревью', engTitle: 'review' },
        spentTime: '1ч',
        plannedTime: '6ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
        ],
    },
    {
        key: 'TR-41',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'paused',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Разработка компонента фильтрации данных',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Ревью', engTitle: 'review' },
        spentTime: '1ч',
        plannedTime: '7ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
        ],
    },
    {
        key: 'TR-45',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'paused',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Создание карточки товара с динамическим контентом',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '2ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
        ],
    },
    {
        key: 'TR-48',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'paused',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Настройка и интеграция системы отображения уведомлений',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '45м',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
        ],
    },
    {
        key: 'TR-56',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'paused',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Создание кастомного компонента для загрузки файлов',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '',
        plannedTime: '1ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
        ],
    },
    {
        key: 'TR-67',
        project: { icon: '/icons/project-icon.svg', title: 'Simplanum' },
        product: {
            icon: '/icons/iOS.svg',
            title: 'iOS',
        },
        version: 1.12,
        feature: 'Вопрос по процедуре',
        currentTaskStep: 'paused',
        assignee: {
            name: 'Вильгельмина',
            surname: 'Шавшина',
            avatarPath: '/avatar.png',
        },
        content: 'Реализация эффекта параллакса для секции сайта',
        category: 'develop',
        department: 'frontend',
        iconBgColor: '#52A7AC',
        status: { title: 'Исполнение', engTitle: 'progress' },
        spentTime: '3ч',
        plannedTime: '10ч',
        stages: [
            { label: 'Этап 1', step: 'completed' },
            { label: 'Этап 2', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
            { label: 'Этап 3', step: 'pending' },
        ],
    },
];
